<div class="container">
         <!-- Top header section -->
         <div class="top-header">
            <div class="left-header">
               <div class="logo">
                  <img src="images/MY COMPANY.COM.svg" alt="My Company" title="Logo" />
               </div>
            </div>
            <div class="nav-bar">
               <a href="#">Edit</a>
               <a href="#">New Arrivals</a>
               <a href="#">Designers</a>
               <a href="#">Clothing</a>
               <a href="#">Shoes</a>
               <a href="#">Accessories</a>
               <a href="#">Jewelry</a>
               <a href="#">Beauty</a>
               <a href="#">Home</a>
            </div>
            <div class="right-header">
               <div class="search-box">
                  <img src="images/Search.svg" alt="Search" title="Search" />
               </div>
               <div class="cart-icon">
                  <img src="images/Bag.svg" alt="cart" title="cart" />
               </div>
               <div class="account-icon">
                  <img src="images/Account.svg" alt="account" title="account" />
               </div>
                <div class="account-icon desktopIcon" onclick="myFunction()">
                  <img src="images/Nav.svg" alt="account" title="account" />
               </div>
            </div>
         </div>
         </div>